package com.kowaisugoi.game.control.flags;

public enum FlagId {
    FLAG_BODY_FOUND,
    FLAG_CAR_FOUND,
    FLAG_CAR_SNOWREMOVED,
    FLAG_SHED_OPENED,
    FLAG_NIGHT_TIME,
    FLAG_BOARDS_REMOVED,
    FLAG_TORCH_PLACED,
    FLAG_ENTERED_BATHROOM,
    FLAG_KEYS_MISSING,
    FLAG_KEYS_FOUND
}
